[package]
authors = ["Dragan Rakita <dragan0rakita@gmail.com>"]
description = "revm - Rust Ethereum Virtual Machine"
edition = "2021"
keywords = ["no_std", "ethereum", "evm", "revm"]
license = "MIT"
name = "revm"
repository = "https://github.com/bluealloy/revm"
version = "3.5.0"
readme = "../../README.md"

[dependencies]
revm-interpreter = { path = "../interpreter", version = "1.3.0", default-features = false }
revm-precompile = { path = "../precompile", version = "2.2.0", default-features = false }

#misc
auto_impl = { version = "1.1", default-features = false }

# Optional
serde = { version = "1.0", features = ["derive", "rc"], optional = true }
serde_json = { version = "1.0", features = ["preserve_order"], optional = true }

# ethersdb
tokio = { version = "1.33", features = [
    "rt-multi-thread",
    "macros",
], optional = true }
ethers-providers = { version = "2.0", optional = true }
ethers-core = { version = "2.0", optional = true }
futures = { version = "0.3.29", optional = true }

[dev-dependencies]
ethers-contract = { version = "2.0.13", default-features = false }
anyhow = "1.0.75"
criterion = "0.5"

[features]
default = ["std", "c-kzg", "serde", "memory_limit", "optional_eip3607", "optional_block_gas_limit", "optional_no_base_fee", "secp256k1", "optimism"]
std = ["revm-interpreter/std", "revm-precompile/std"]
serde = ["dep:serde", "dep:serde_json", "revm-interpreter/serde"]
arbitrary = ["revm-interpreter/arbitrary"]

optimism = ["revm-interpreter/optimism", "revm-precompile/optimism"]

ethersdb = ["std", "tokio", "futures", "ethers-providers", "ethers-core"]

dev = [
    "memory_limit",
    "optional_balance_check",
    "optional_block_gas_limit",
    "optional_eip3607",
    "optional_gas_refund",
    "optional_no_base_fee",
    "optional_beneficiary_reward",
]
memory_limit = ["revm-interpreter/memory_limit"]
no_gas_measuring = ["revm-interpreter/no_gas_measuring"]
optional_balance_check = ["revm-interpreter/optional_balance_check"]
optional_block_gas_limit = ["revm-interpreter/optional_block_gas_limit"]
optional_eip3607 = ["revm-interpreter/optional_eip3607"]
optional_gas_refund = ["revm-interpreter/optional_gas_refund"]
optional_no_base_fee = ["revm-interpreter/optional_no_base_fee"]
optional_beneficiary_reward = ["revm-interpreter/optional_beneficiary_reward"]

# See comments in `revm-precompile`
secp256k1 = ["revm-precompile/secp256k1"]
c-kzg = ["revm-precompile/c-kzg"]

# deprecated features
web3db = []
with-serde = []

[[example]]
name = "fork_ref_transact"
path = "../../examples/fork_ref_transact.rs"
required-features = ["ethersdb"]

[[bench]]
name = "bench"
path = "benches/bench.rs"
harness = false
